<a href="https://colab.research.google.com/github/khushboo-garg/SMCR/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Khushboo Garg
#import packages
import numpy as np
#from np import array - doesn't work because np is an alias not a module; np.array would work directly
from numpy import array
from numpy.linalg import inv as inv

In [2]:
#create arrays and do maths
a1 = [5,8,13]
a2 = array ([5,8,13])
#a2 = np.array([5, 8, 13]) - this would also work!
a = array([[5,8,13]])
a.shape

(1, 3)

In [3]:
#TRANSPOSE
# b1 = a1.T -> list object has no attribute 'T'
b2 = a2.T #no affect of transpose because a2 is a flat vector. Transpose works on 2D
b = a.T
b

#MULTIPLICATION & INNER PRODUCT
c1 = a1 * 2 #does not perform element wise multiplication; concatenates this list
c2 = a2 * 2 #element-wise operation
c = a * 2 #element-wise operation
c1, c2, c

x = array ([9,8,7]) * array ([11, 10, 9]) #each element in the first array is multiplied by the corresponding element in the second array
x = b^3 #bitwise XOR between each element and the integer - decimals converted to binary and then XOR performed on bit pairs. Resulting binary is converted back into decimals
d = b**3 #element-wise cubing
d

p1 = a*b #broadcasted to 3*3 and element wise multiplication
p2 = a * b.T
p3 = a.T * b
p1, p2, p3

(array([[ 25,  40,  65],
        [ 40,  64, 104],
        [ 65, 104, 169]]),
 array([[ 25,  64, 169]]),
 array([[ 25],
        [ 64],
        [169]]))

In [4]:
p4 = a @ b #matrix multiplication - inner product
p4
#p5 = a @ b.T dimension mismatch
#p6 = a.T @ b dimension mismatch
p7 = a.T @ b.T #outer product [3*1] * [1*3] = [3*3]
p8 = a2 @ b2 #inner product
p9 = a2.T @ b2 #inner product
p4, p7, p8, p9

(array([[258]]),
 array([[ 25,  40,  65],
        [ 40,  64, 104],
        [ 65, 104, 169]]),
 np.int64(258),
 np.int64(258))

In [5]:
#DIVISION
q1 = a / b.T #element wise division
q1 = a.T / b #element wise division
q1 = a / b #broadcasted to 3*3 and then element wise division
# q2 = a \ b -> "\" unexpected character - error
q1

array([[1.        , 1.6       , 2.6       ],
       [0.625     , 1.        , 1.625     ],
       [0.38461538, 0.61538462, 1.        ]])

In [6]:
#VECTOR MISTAKES
y = array([1,2,3,4])
#y_error = y[1.0] #indexing with float doesn't work. needs Integer
y_correct = y[1]
y_correct

#z = [1,2,3] ** 2 #power doesn't work on list
z = [1,2,3]
z_power = array(z) ** 2
z_power

array([1, 4, 9])

In [7]:
#MULTI DIMENSIONAL ARRAYS
A1 = [b, b+21, b**2] # list of 2D arrays
A1
#A2 = array (b, b+21, b**2) array() takes from 1 to 2 positional arguments but 3 were given -
# the array function is typically used to create an array from a single list or tuple of elements.
A = np.vstack([a, a+21, a**2]) #2D array vertically stacked resulting in a 3*3 array
x = inv(A) @ b # solves A*x=b for x
z = A @ x - b # A(3*3) @ x(3,1) resulting in a (3,1) matrix shape which is same as b, so element vise subtraction
# since x was solved for Ax=b, A@x should be b - which should ideally be 0 (but floating point inaccuracies)
AtA = A.T @ A #symmetric non-negative matrix
z, AtA

(array([[-1.77635684e-15],
        [-1.33226763e-14],
        [ 3.55271368e-15]]),
 array([[ 1326,  2394,  5174],
        [ 2394,  5001, 11906],
        [ 5174, 11906, 29886]]))

In [8]:
#stacking arrays horizontally and vertically
B = np . hstack ([ b , b **2 ]) # horizontally stacks two (3,1) shape arrays resulting in (3,2) shape array
C = np . vstack ([ c +21 , c **2 ]) # vertically stacks two (1,3) shape arrays resulting in (2,3) shape array
D = array ([ [1 ,2] , [3 ,4] ]) # created a (2,2) array from list
S = np . vstack ([ np . hstack ([ A , B ]) , np . hstack ([ C , D ]) ]) # [ A , B ; C , D ]
# np . hstack ([ A , B ]) horizontally stacks A(3,3) and B (3,2) to form (3,5) array
# np . hstack ([ C , D ]) horizontally stacks C(2,3) and D(2,2) to form (2,5) array
# finally np.vstack vertically stacks the resulting (3,5) and (2,5) array to form (5,5) array
B,C,D,S

(array([[  5,  25],
        [  8,  64],
        [ 13, 169]]),
 array([[ 31,  37,  47],
        [100, 256, 676]]),
 array([[1, 2],
        [3, 4]]),
 array([[  5,   8,  13,   5,  25],
        [ 26,  29,  34,   8,  64],
        [ 25,  64, 169,  13, 169],
        [ 31,  37,  47,   1,   2],
        [100, 256, 676,   3,   4]]))

In [9]:
#ARRAY MISTAKES
E = np.array([[1,2,3],[3,4,5]])
#E_error = np.hstack([E, np.array([[5,6,7]])])  # !! ValueError: all arrays must have same number of rows

# Fix for hstack: The array to hstack must have the same number of rows as E (which is 2)
E_fix = np.hstack([E, np.array([[5],[6]])]) # Corrected: Stacking a 2x1 array
print("E_fix (hstack): ", E_fix)

F = np.array([[1,2],[3,4],[5,6]])

# F_error = np.vstack([F, np.array([[5],[6],[7]])])  # !! ValueError: all arrays must have same number of columns as F (which is 2)
F_fix = np.vstack([F, np.array([[5,6],[7,8]])]) # Corrected: Stacking a 1x2 array
print("F_fix (vstack): ", F_fix)

E_fix (hstack):  [[1 2 3 5]
 [3 4 5 6]]
F_fix (vstack):  [[1 2]
 [3 4]
 [5 6]
 [5 6]
 [7 8]]


In [10]:
#creating array
# u = [ 0 : 10 ] # syntax error
u = np.linspace (1 ,10 ,10) # np.linspace creates an array starting from 1 to 10, at 10 equal intervals
u

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
#indexing arrays
# v = u [10] # indexing starts at 0
v = u [0] # returns first element of array
v = u [ -1] # returns last element of array
v = u[2:5] #returns index 2 to 4;not including 4 and since indexing starts at 0  3rd, 4th and 5th element
v = u [2:5+1] #returns index 2 to 5
v = A [2 , 0] #2D array with row m and col n -> array [m,n] -> so 2,0 means 2nd row and 0th col (indexing at 0)
v = A [2][0] #another way to access array element - same as A[2,0]
v = A [1 ,:] # : means "all elements" so [1,:] => 1st row (0 indexing) and all columns in that row
v = A [1:3 ,:] #1st and 2nd row (0 indexing) and all columns
v = A [1:3 ,1:3] # rows 1 and 2; columns 1 and 2
v = u [6: -2:2] #[start:stop:step] -> starts at 6th element, goes up till (not including) element at index -2 (second last element), and selects every second element along the way
v = u [[6 ,4 ,2]] #returns elements at the specified indices in the list
v

array([7., 5., 3.])

In [12]:
np.set_printoptions(precision=20) # high level of precision
sp = np.sin( np.pi/2) # Sin(pi/2) = 1.0
error = sp - 1 # comes exactly zero
print (" sin ( pi /2): " , sp )
print (" error : " , error )

 sin ( pi /2):  1.0
 error :  0.0


In [13]:
# example ( b )
err_gr = 0.0
err_05 = 0.0
err_08 = 0.0
err_11 = 0.0
err_20 = 0.0
err_22 = 0.0
err_32 = 0.0
err_35 = 0.0
gr = ( np.sqrt(5) - 1.0)/2.0

for x in range (0 , 100000): # for-loop in Python - the mathematical expression inside abs() should be zero but floating point arithmetic introduces small inaccuracies
    err_gr += abs(x - (1.0/ gr ) * x * gr )
    err_05 += abs(x - (1.0/05.0) * x * 05.0)
    err_08 += abs(x - (1.0/08.0) * x * 08.0)
    err_11 += abs(x - (1.0/11.0) * x * 11.0)
    err_20 += abs(x - (1.0/20.0) * x * 20.0)
    err_22 += abs(x - (1.0/22.0) * x * 22.0)
    err_32 += abs(x - (1.0/32.0) * x * 32.0)
    err_35 += abs(x - (1.0/35.0) * x * 35.0)

print (" err_gr :" , err_gr ) # not zero
print (" err_05 :" , err_05 ) # not zero
print (" err_08 :" , err_08 ) # exactly zero
print (" err_11 :" , err_11 ) # not zero
print (" err_20 :" , err_20 ) # not zero
print (" err_22 :" , err_22 ) # not zero
print (" err_32 :" , err_32 ) # exactly zero
print (" err_35 :" , err_35 ) # not zero

 err_gr : 1.0034440034445424e-07
 err_05 : 1.3704605672515413e-07
 err_08 : 0.0
 err_11 : 7.896045595146006e-08
 err_20 : 1.3704605672515413e-07
 err_22 : 7.896045595146006e-08
 err_32 : 0.0
 err_35 : 1.4667781922383938e-07


Ques: How are the numbers 8 and 32 qualitatively different from 5, 11, 20, 22, or 35?

Ans: 8 and 32 are powers of 2 and have exact representation in binary floating point arithmetic so the calculations can be performed precisely.

Ques: Under what conditions would you say that a result of 10^-6 is negligibly small?

Ans: Whether 10^-6 is “negligible” depends on the scale of the quantity and the required relative tolerance. For e.g., for global mean temperatures the order of 10^-6 is too small, but if you are trying to study tiny signals of magnitude 10^-6, this would be quite large!

In [14]:
#iterating 100 times - errors are much smaller (1000 times)
for x in range (0 , 100): # for-loop in Python - the mathematical expression inside abs() should be zero but floating point arithmetic introduces small inaccuracies
    err_gr += abs(x - (1.0/ gr ) * x * gr )
    err_05 += abs(x - (1.0/05.0) * x * 05.0)
    err_08 += abs(x - (1.0/08.0) * x * 08.0)
    err_11 += abs(x - (1.0/11.0) * x * 11.0)
    err_20 += abs(x - (1.0/20.0) * x * 20.0)
    err_22 += abs(x - (1.0/22.0) * x * 22.0)
    err_32 += abs(x - (1.0/32.0) * x * 32.0)
    err_35 += abs(x - (1.0/35.0) * x * 35.0)

print (" err_gr :" , err_gr ) # not zero
print (" err_05 :" , err_05 ) # not zero
print (" err_08 :" , err_08 ) # exactly zero
print (" err_11 :" , err_11 ) # not zero
print (" err_20 :" , err_20 ) # not zero
print (" err_22 :" , err_22 ) # not zero
print (" err_32 :" , err_32 ) # exactly zero
print (" err_35 :" , err_35 ) # not zero

 err_gr : 1.0034450603768619e-07
 err_05 : 1.3704621171228837e-07
 err_08 : 0.0
 err_11 : 7.896052878209048e-08
 err_20 : 1.3704621171228837e-07
 err_22 : 7.896052878209048e-08
 err_32 : 0.0
 err_35 : 1.466779604442081e-07
